import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Sensei Node</h1>
        <Link as="/signature/senseinode_black.png" href="/signature/[id]" passHref={true}>
          <button className={styles["button"]}>Sensei Node Logo</button>
        </Link>
        <Link as="/signature/linkedinlogo.png" href="/signature/[id]" passHref={true}>
          <button className={styles["button"]}>Linkedin Logo</button>
        </Link>
      </main>
    </div>
  );
}
