import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { useRouter } from "next/router";


const SignaturePage = () => {
    const router = useRouter();
    const { id } = router.query;
    return (
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <img className={styles["logo"]} src={`/assets/signature/${id}`} alt={id} />
        </main>
      </div>
    )
}
export default SignaturePage;