import Head from 'next/head';
import styles from '../../styles/Home.module.css';

const SignaturePage = ({id}) => {
    return (
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <img className={styles["logo"]} src={`/assets/signature/${id}`} alt={id} />
        </main>
      </div>
    )
}

export async function getServerSideProps({params}) {
    return {
        props: {
            id: params.id
        }
    }
}

export default SignaturePage;