/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

import styles from "../../styles/Home.module.css";

const SignaturePage = ({ id }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
      </Head>
      <main className={styles.main}>
        <img alt={id} className={styles["logo"]} src={`/assets/signature/${id}`} />
      </main>
    </div>
  );
};

export async function getServerSideProps({ params }) {
  return {
    props: {
      id: params.id
    }
  };
}

export default SignaturePage;
